### ISSUE TITLE
Document image-based workaround for Line2D antialiasing

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#4441]
**Your Godot version:** 3.2.3

**Issue description:**

Line2D's antialiasing property is known not to be reliable:

- [It sometimes doesn't work if HDR is enabled in the project settings (which is the default when using GLES3).](https://github.com/godotengine/godot/issues/38872)
- [It breaks with translucent lines (alpha < 1.0).](https://github.com/godotengine/godot/issues/35878)

Fortunately, you can use a specially crafted image for the Line2D to solve *most* of the aliasing issues with no performance impact. It won't anti-alias the line's begin and end caps (unless a circular cap mode is used), though. See https://www.reddit.com/r/godot/comments/k7qcwa/when_im_using_a_line2d_node_im_getting_horrible/.

When Mipmaps is enabled on the line texture, it should be possible to use a relatively tall image (like 1×128) to support pretty much every common line width, with good scaling support when using the `2d` stretch mode.

See also https://github.com/godotengine/godot-docs/issues/2379.

**URL to the documentation page (if already existing):** https://docs.godotengine.org/en/latest/classes/class_line2d.html

**Comment by Calinou** [comment]
Note that following the merge of https://github.com/godotengine/godot/pull/43828, Line2D antialiasing *should* work reliably in 4.0. We should still document this workaround for 3.2.x.

**Comment by michaldev** [comment]
Drawing a straight 2d line is one of the basic functions of the engine. I can't find a solution to my problem anywhere and my thread has been closed.

This work very well on unity and defold.

**Comment by michaldev** [comment]
Yes. It doesn't work.
![image](https://user-images.githubusercontent.com/5132385/153155449-f80f9ecb-e440-4a36-8c4c-057921e05eca.png)

**Comment by Calinou** [comment]
@michaldev It appears you're using a very bright color for your text, line and circle:

![image](https://user-images.githubusercontent.com/180032/153239556-5889a937-25eb-4e10-b4eb-9100877dd365.png)

This is the reason for a green fringe line appearing. Check the values of your various colors in your scene, including Modulate and Self Modulate properties – they must be between 0 and 1, not a brighter value.

**Comment by hazarek** [comment]
godot 4 alpha 3 still no antialiased thin lines. We are not in the 80s.

**Comment by Calinou** [comment]
> godot 4 alpha 3 still no antialiased thin lines. We are not in the 80s.

The Vulkan renderer features portable line antialiasing using triangle strips: https://github.com/godotengine/godot/pull/43828

However, the `antialiased` parameter was removed for some of the line drawing functions.

**Comment by Calinou** [comment]
I recently released an add-on which automates the process described in this issue: https://github.com/godot-extended-libraries/godot-antialiased-line2d

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/59952.

**Comment by MathiasBaumgartinger** [comment]
> I recently released an add-on which automates the process described in this issue: https://github.com/godot-extended-libraries/godot-antialiased-line2d
> 
> It supports antialiased 2D line and polygon drawing.

I just played around with a project in Godot 4 Beta that uses Line2D, I know this is more of a feature-request/bug-report but I first want to verify I understood your comment (and the `/latest`-documentation) correctly: Antialiasing should no longer be a problem on Line2D once the `Antialiased` property in the section `border` is checked in Godot 4, right? Because I am still getting a very "pixeled" line even when using the property:

![image](https://user-images.githubusercontent.com/33001106/199053112-da4e7be6-5950-4ac7-971f-f6aed21401ca.png)

**Comment by Calinou** [comment]
> Antialiasing should no longer be a problem on Line2D once the Antialiased property in the section border is checked in Godot 4, right?

Indeed, triangle strip antialiasing was implemented in Godot 4.

> Because I am still getting a very "pixeled" line even when using the property:

Check the line's color – is it standard white (`Color(1, 1, 1)`) and not *overbright* (`Color(255, 255, 255)`)? Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by MathiasBaumgartinger** [comment]
Thanks for letting me know, excuse my unnecessary comment.
