### ISSUE TITLE
TSCN files are NOT compiled into binary .scn

### ISSUE THREAD

**Issue by Listwon** [godotengine/godot-docs#5131]
### Godot version

Godot Engine v3.3.2.stable.official

### System information

Windows 10

### Issue description

According to [documentation](https://docs.godotengine.org/en/stable/development/file_formats/tscn.html): `During import, TSCN files are compiled into binary .scn`. The problem is - they are not.

Changing `.tscn` extension to `.escn` triggers proper import and the scene is converted to `.scn` and saved in the `.import` folder.

### Steps to reproduce

Create empty project and add new scene. Save the scene as `.tscn`. It won't be imported to `.import` folder as `.scn` file (as it should).

**Comment by Listwon** [comment]
@Calinou this is a different topic. `convert_text_resources_to_binary_on_export` generates .tscn.converted.res files and they are not "compressed" as .scn are in comparison to .tscn. Saving the scene as `.scn` gives similar output to changing `.tscn` extension to `.escn`.

**Comment by Calinou** [comment]
`.escn` is meant to be exported from external software such as Blender *as a 3D scene*. It is not relevant for 2D scenes and the like.

**Comment by Listwon** [comment]
That's not what I meant and it's not the real issue here.

**Comment by Calinou** [comment]
> That's not what I meant and it's not the real issue here. Please revert the title.

Are you talking in a 2D or 3D context here? I'm pretty sure the current behavior is intended. There is no need to "import" scenes unless they come from a 3D DCC. They only need to be loaded, which is why you can load arbitrary PackedScenes at run-time (you can't do this with Collada/glTF, for instance).

**Comment by Listwon** [comment]
Of course there is, to save them as PackedScene in binary .scn format.

**Comment by Calinou** [comment]
> Of course there is, to save them as PackedScene in binary .scn format.

To do so, open the `.tscn` file in the editor, use **Scene > Save As...** and replace the file extension with `.scn`.

**Comment by Listwon** [comment]
But as I stated in the first post - according to documentation it should convert automatically ^^'
```C++
Node *EditorSceneImporterESCN::import_scene(const String &p_path, uint32_t p_flags, int p_bake_fps, List<String> *r_missing_deps, Error *r_err) {
	Error error;
	Ref<PackedScene> ps = ResourceFormatLoaderText::singleton->load(p_path, p_path, &error);
	ERR_FAIL_COND_V_MSG(!ps.is_valid(), nullptr, "Cannot load scene as text resource from path '" + p_path + "'.");

	Node *scene = ps->instance();
	ERR_FAIL_COND_V(!scene, nullptr);

	return scene;
}
```
does exactly that with `.escn` which according to documentation is actually the TSCN format.

TSCN is CVS friendly, so it's better during development but for exported build binary scn format is better.

**Comment by Calinou** [comment]
The thing is that unlike ESCN, TSCN is not meant to receive automatic modifications by Godot. There are no colliders to create, no animations to bake, etc.

**Comment by Listwon** [comment]
And yet you use exactly the same loader to load it as PackedScene, so technically it doesn't matter.
`ResourceFormatLoaderText::singleton->load(p_path, p_path, &error);`

**Comment by Listwon** [comment]
Even @Zylann thought it works as I stated in the first post
https://godotengine.org/qa/70831/will-exported-tscn-become-scn

**Comment by pycbouh** [comment]
> But as I stated in the first post - according to documentation it should convert automatically ^^'

The documentation is simply incorrect. `.escn` is a scene file format that is produced by an external program. Everything that is produced by an external program is imported into the project, and an imported representation is created in the `.import` folder. `.tscn` is a scene file format that you manually create while working with a Godot project. At no point does it get imported.

The documentation has nothing to do with *exporting* projects. When a project is exported all Godot's text resource files are converted to binary format automatically.

**Comment by Listwon** [comment]
@pycbouh `When a project is exported all Godot's text resource files are converted to binary format automatically.` NO THEY ARE NOT. This is the real issue here. TSCN files are not converted to binary format. I checked both zip and pck outputs.

**Comment by Listwon** [comment]
@akien-mga please help here

**Comment by pycbouh** [comment]
> NO THEY ARE NOT. This is the real issue here. TSCN files are not converted to binary format. I checked both zip and pck outputs.

You're right, `convert_text_resources_to_binary_on_export` needs to be turned on. Your initial report is still incorrect.

**Comment by Listwon** [comment]
TSCN files are stored as text files even in exported builds (pck, zip).

**Comment by Calinou** [comment]
> Why is it closed? You changed the title to your liking and closed with irrelevant PR.

I didn't change this issue's title; I only transferred this issue.

Also, I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by groud** [comment]
> Why is it closed? You changed the title to your liking and closed with irrelevant PR.

The issue was closed automatically when #5132 got merged. As it is making clear that `tscn`  file are not supposed to be converted at import time, the issue seems indeed solved, as the documentation was simply wrong.

**Comment by Listwon** [comment]
> You're right, `convert_text_resources_to_binary_on_export` needs to be turned on. Your initial report is still incorrect, as the article you've mentioned doesn't cover that matter at all.

Calinou mentioned the issue with this property and I just explained that I'm talking about something different as I also tried this option and it wasn't what I was expecting - converting tscn to scn

> is also incorrect, as `.tscn.converted.res` files are in fact binary.
binary, but it gives different output than saving as .scn or converting .escn to .scn at real time. 

For example:
Main.scn
Main.escn-7892a1b93e31d6efc1ba93d644da7b47.scn
Main.tscn.converted.res

Created from the same TSCN text, each is different.

I assumed that it would be better to fix the behaviour rather than changing the documentation, but in case of changing docs, please also inform people in mentioned Q&A question that it's not true
https://godotengine.org/qa/70831/will-exported-tscn-become-scn

**Comment by akien-mga** [comment]
> For example:
> Main.scn
> Main.escn-7892a1b93e31d6efc1ba93d644da7b47.scn
> Main.tscn.converted.res
> 
> Created from the same TSCN text, each is different.

How do they differ? In case it's not clear, `.scn` and `.res` are the exact same thing. They're two synonymous extensions for the binary serialization of `Resource`s.

**Comment by Listwon** [comment]
They differ binary, I've just compared them in HxD
![res](https://user-images.githubusercontent.com/1554127/127698625-c084960b-7533-4426-ab09-0252a0fb7c70.jpg)
![scn](https://user-images.githubusercontent.com/1554127/127698631-9bf32ab7-e83d-400f-a77c-ea52cbf13864.jpg)

**Comment by akien-mga** [comment]
The difference seems to be that one is compressed (`RSCC`) while the other one is not (`RSRC`).
But both are indeed **binary .scn** formats (`core/io/resource_format_binary.h`).

So while one might question why one gets compressed and not the other, it seems to me that:
- The documentation which was wrong and referenced in the OP has been correctly fixed.
- The title of this issue is not factually correct.
- The `editor/convert_text_resources_to_binary_on_export` setting works (as a side note it seems to be missing from the class reference as it's defined only in editor code, this should be fixed).
- Why export conversion of text-based resources to binary resources doesn't involve compression is worth looking into.

**Comment by akien-mga** [comment]
Test project with scenes and resources in the following formats:
- Scene: TSCN, SCN, ESCN, TSCN inherited from imported ESCN
- Non-scene Resource: TRES, RES

Includes an export to ZIP with `editor/convert_text_resources_to_binary_on_export` enabled.

[TestProject.zip](https://github.com/godotengine/godot-docs/files/6909545/TestProject.zip)

That confirms the above findings, unlike manually saving text-based formats to binary formats, the export conversion to binary does not involve compression.

**Comment by Listwon** [comment]
`editor/convert_text_resources_to_binary_on_export` is still broken as Calinou confirmed it here https://github.com/godotengine/godot/issues/42115

**Comment by akien-mga** [comment]
> `editor/convert_text_resources_to_binary_on_export` is still broken as Calinou confirmed it here [godotengine/godot#42115](https://github.com/godotengine/godot/issues/42115)

That's a bug on a very corner case (a dictionary where Resources are used as keys...), that's not really related to this issue. That doesn't make the setting "broken" more than any bug makes the whole Godot Engine "broken". It breaks that very specific use case only.

We're mixing a lot of loosely related topics in an issue which started with two short paragraphs, that's not really the best workflow for us to work efficiently on separate issues (we do have some `[TRACKER]` issues which aim at listing all bugs related to a given concept, but this wasn't started as one).

**Comment by mhilbrunner** [comment]
@Listwon Sorry I missed this discussion here when merging the above PR. No ill will intended :)
