### ISSUE TITLE
A mistranslation of "Core features" in zh-tw.

### ISSUE THREAD

**Issue by StellarH** [godotengine/godot-docs#9004]
**Your Godot version:**
4.x

**Issue description:**
The translation of `Core feature` in language `zh-tw` is mistranslated as `C# 功能` means C# features.
That should be correct as `核心功能`.

**URL to the documentation page:**
https://docs.godotengine.org/zh-tw/4.x/tutorials/scripting/index.html#core-features

**Comment by AThousandShips** [comment]
Translations are edited on the webplate, see [here](https://docs.godotengine.org/en/stable/contributing/documentation/editor_and_docs_localization.html), you can do this yourself :)

**Comment by DidierMorandi** [comment]
I did the search for you. register within Weblate (see here: https://docs.godotengine.org/en/latest/contributing/documentation/contributing_to_the_documentation.html)
then go to https://hosted.weblate.org/translate/godot-engine/godot-docs/zh_Hant/?q=core+features&sort_by=-priority%2Cposition&offset=8
You will be able then to correct the translation. The Weblate interface is really easy to learn.
Enjoy.

**Comment by Mickeon** [comment]
Can anybody with understanding of the language verify that this has been corrected?

**Comment by tetrapod00** [comment]
> Can anybody with understanding of the language verify that this has been corrected?

It looks like it's still translated as `C# 功能` in the linked weblate page. In the actual docs page, it appears to me as `Core Features` in English.

But as a rule we don't really use the docs repo to track the translation status of specific strings. So even though this is still not translated correctly, we shouldn't keep this issue open.

Since the link to edit this string has been shared, I'm closing this as something we don't track in this repo.
